export const clothingCategories = [
  "top",
  "bottom",
  "one_piece",
  "outerwear",
  "shoes",
  "bag",
  "jewelry",
  "headwear",
  "scarf",
  "belt",
  "eyewear",
  "hair_accessory",
  "other_accessory",
] as const;

export const colorIds = [
  "black",
  "white",
  "gray",
  "beige",
  "brown",
  "navy",
  "blue",
  "green",
  "red",
  "pink",
  "purple",
  "yellow",
  "orange",
  "metallic",
  "multicolor",
] as const;

export const commonMaterials = [
  "Cotton",
  "Denim",
  "Knit",
  "Wool",
  "Linen",
  "Leather",
  "Suede",
  "Silk",
  "Satin",
  "Polyester",
  "Nylon",
  "Fleece",
] as const;

export const categoryLabels: Record<(typeof clothingCategories)[number], string> = {
  top: "Tops",
  bottom: "Bottoms",
  one_piece: "Dresses & Jumpsuits",
  outerwear: "Outerwear",
  shoes: "Shoes",
  bag: "Bags",
  jewelry: "Jewelry",
  headwear: "Hats",
  scarf: "Scarves",
  belt: "Belts",
  eyewear: "Eyewear",
  hair_accessory: "Hair Accessories",
  other_accessory: "Other Accessories",
};

export const colorLabels: Record<(typeof colorIds)[number], string> = {
  black: "Black",
  white: "White",
  gray: "Gray",
  beige: "Beige",
  brown: "Brown",
  navy: "Navy",
  blue: "Blue",
  green: "Green",
  red: "Red",
  pink: "Pink",
  purple: "Purple",
  yellow: "Yellow",
  orange: "Orange",
  metallic: "Metallic",
  multicolor: "Multicolor",
};

export const colorHex: Record<(typeof colorIds)[number], string> = {
  black: "#111111",
  white: "#ffffff",
  gray: "#a4a4a8",
  beige: "#dfccb0",
  brown: "#75523c",
  navy: "#30384d",
  blue: "#3f7fc4",
  green: "#3f8b5c",
  red: "#d6383b",
  pink: "#e6a2b3",
  purple: "#8350a7",
  yellow: "#f1c84a",
  orange: "#e9862d",
  metallic: "linear-gradient(135deg,#777,#fff,#777)",
  multicolor: "conic-gradient(#e83b45,#f0ca45,#4b9b61,#4b7ec7,#9b57b5,#e83b45)",
};

export const wardrobeFilterLabels = [
  "All",
  "Tops",
  "Bottoms",
  "Outerwear",
  "Shoes",
  "Accessories",
] as const;
